# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# Overwrite or add rules to create your own house style
#
# # Use `[a, [b, c]]` not `[ a, [ b, c ] ]`
RSpec/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
  Severity: warning

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Layout/IndentationStyle:
  Enabled: true
  Style: space

Layout/AlignParameters:
  EnforcedStyle: with_fixed_indentation

Layout/BlockAlignment:
  Enabled: true
  EnforcedStyle: each

Layout/IndentationConsistency:
  Enabled: true
  EnforcedStyle: normal

Layout/IndentationWidth:
  Enabled: true
  Width: 2

Layout/TrailingWhitespace:
  Enabled: true
  Severity: error

Layout/TrailingEmptyLines:
  Enabled: true
  EnforcedStyle: final_newline

Layout/EmptyLines:
  Enabled: true

Layout/EmptyLinesAroundClassBody:
  Enabled: true
  EnforcedStyle: empty_lines

Style/StringLiterals:
  Description: "Enforce the use of single quotes except when string contains interpolation"
  Enabled: true
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes
  ConsistentQuotesInMultiline: true

Style/PercentLiteralDelimiters:
  Description: "Use `%`-literal delimiters consistently"
  Enabled: true
  PreferredDelimiters:
    "%": "()"
    "%i": "[]"
    "%I": "[]"
    "%q": "()"
    "%Q": "()"
    "%r": "{}"
    "%s": "()"
    "%w": "[]"
    "%W": "[]"
    "%x": "()"
