name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      ruby_version: ${{ steps.ruby-version.outputs.ruby_version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Install Bundler and Gems
        run: |
          gem install bundler
          bundle install

  scan_ruby:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Scan for common Rails security vulnerabilities using static analysis
        run: |
          bundle exec brakeman --no-pager

  lint:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Lint code for consistent style
        run: |
          bundle exec rubocop -f github

  test:
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Run tests
        env:
          RAILS_ENV: test
        run: |
          bin/rails db:test:prepare
          bundle exec rspec

      - name: Keep screenshots from failed system tests
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: ${{ github.workspace }}/tmp/screenshots
          if-no-files-found: ignore
